### PR TITLE
fix: stability and bug fixes 

### LINKED ISSUE #133: bug: startup scripts hang on "Checking for required secrets"
**Describe the bug**
As noted in the title, the startup scripts hang looking for the database passwords; the workaround is to add these manually to the configuration file:

```
          pulumi config set sirius:accounts_pwd --secret "Password" -C pulumi/python/kubernetes/applications/sirius -s marajenkaws${BUILD_NUMBER}
          pulumi config set sirius:ledger_pwd --secret "Password" -C pulumi/python/kubernetes/applications/sirius -s marajenkaws${BUILD_NUMBER}
```

**To Reproduce**
1. Run deployment w/o setting passwords first.
2. Deployment will hang.

**Expected behavior**
Deployment should work as designed.

**Your environment**
n/a

**Additional context**
Most likely introduced by #131

### PR DESCRIPTION
**Pull request by qdzlug**
### Proposed changes
There are a number of small changes included in this PR. 
- Requirements have been updated to the most recent supported version; note #134 as to why pulumi-docker is being held back and #137 on why we are holding back the EKS version.
- Erroneous dash removed from linode start script; this was preventing the script from running.
- Fixes were added to createpw() function to get around the issue where scripts using the function would hang when calling /dev/urandom from Jenkins (closes #133)
-  Other fixes and enhancements to Jenkinsfiles; included removing the no longer used POST_CMD as well as correcting syntax errors the Jenkins linter missed (unterminated sh blocks).
- Added Pulumi args to scripts (the stack name was not getting passed for some AWS startup steps).
- Documentation updates.

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [X] I have written my commit messages in the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) format. 
- [X] I have read the [CONTRIBUTING](/CONTRIBUTING.md) doc
- [X] I have added tests (when possible) that prove my fix is effective or that my feature works
- [X] I have checked that all unit tests pass after adding my changes
- [X] I have updated necessary documentation
- [X] I have rebased my branch onto master
- [X] I will ensure my PR is targeting the master branch and pulling from my branch from my own fork

### CODE REVIEW

File: bin/start_aws.sh [hunk 1]
```diff
@@ -152,8 +152,8 @@ else
 fi
 
 function createpw() {
-  base64 /dev/random | tr -dc '[:alnum:]' | head -c${1:-16}
-  return 0
+    PWORD=$(dd if=/dev/urandom count=1  2>/dev/null | base64 | head -c16)
+    echo $PWORD
```
Comment (4141done) [inline bin/start_aws.sh:156]: Two questions:

1. So the fix to get around calling `/dev/random` which was causing jenkins to hang was to read it in using `dd`?  My understanding here is that this is just a different way to read from `/dev/urandom` to bypass a jenkins quirk.  Is that correct?  Just trying to understand how I might make a choice between these two approaches in the future.
2. What purpose is `PWORD` serving here?  Would `echo $(dd if=/dev/urandom count=1  2>/dev/null | base64 | head -c16)` not serve the same purpose?

File: extras/jenkins/Minikube/Jenkinsfile [hunk 2]
```diff
@@ -113,15 +113,10 @@ pipeline {
...
-            source /etc/os-release
-            sh -c "echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list"
-            wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/xUbuntu_${VERSION_ID}/Release.key -O- | apt-key add -
-            apt-get update -qq -y
-            apt-get -qq --yes install podman
             curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64  && chmod +x minikube
             mkdir -p /usr/local/bin/
             install minikube /usr/local/bin/
-            minikube start --vm-driver=podman
+            minikube start --vm-driver=none
```
Comment (4141done) [inline extras/jenkins/Minikube/Jenkinsfile:119]: Question:
What is the reason that we no longer use podman with minikube?

File: extras/jenkins/Minikube/Jenkinsfile [hunk 3]
```diff
@@ -185,6 +180,7 @@ _EOF_
             $WORKSPACE/pulumi/python/venv/bin/pulumi config set prometheus:adminpass "password" -C pulumi/python/config -s marajenk${BUILD_NUMBER}
             $WORKSPACE/pulumi/python/venv/bin/pulumi config set prometheus:helm_timeout "600" -C pulumi/python/config -s marajenk${BUILD_NUMBER}
             $WORKSPACE/pulumi/python/venv/bin/pulumi config set prometheus:helm_timeout "600" -C pulumi/python/config -s marajenk${BUILD_NUMBER}
+            '''
```
Comment (4141done) [inline extras/jenkins/Minikube/Jenkinsfile:183]: oh noooo.  Glad this is fixed 🐳

File: pulumi/python/kubernetes/nginx/ingress-controller-repo-only/__main__.py [hunk 4]
```diff
@@ -31,7 +31,7 @@
     nginx_repository = "nginx/nginx-ingress"
 nginx_tag = config.get('nginx_tag')
 if not nginx_tag:
-    nginx_tag = "2.1.0"
+    nginx_tag = "2.2.0"
```
Comment (4141done) [inline pulumi/python/kubernetes/nginx/ingress-controller-repo-only/__main__.py:34]: Comment: I'm sure you've already thought of this, but it would be really nice if we could somehow colocate all the various versions of things then have the framework internally read them and then put them into contexts like this.  I'm not sure how you'd do it with the python requirements but I see a lot of other versions of things that seem to be existing across various files

**Review by 4141done — APPROVED** [review]
👍 🐳 👍 
This all looks good to me.  I had a few questions and nonblocking comments.  You may want to ask a better unix person than me about the password generation command but I was able to grok it mostly.

File: pulumi/python/kubernetes/nginx/ingress-controller-repo-only/__main__.py (hunk 4 above)
Comment (4141done) [reply pulumi/python/kubernetes/nginx/ingress-controller-repo-only/__main__.py:34]: Filed an issue around this: https://github.com/nginxinc/kic-reference-architectures/issues/140

**Review by 4141done — APPROVED** [review]
👍 🐳 👍 
Looks good to me.  Only change suggestion is the removal of a comment but that's up to you.

File: docs/getting_started.md [hunk 5]
```diff
@@ -48,28 +48,30 @@ $ sudo yum install python3-pip make git docker-ce
...
-$ ./build_dev_docker_image.sh debian
+$ ./docker/build_dev_docker_image.sh debian
 ```
 
 ## Stand Alone Install
 
 ### Requirements
 
-#### Python 3 or Prerequisites for Building Python
+#### Python 3.7 or Newer or Prerequisites for Building Python 3.7 or Newer
```
[the remark this answers is not in the document]
Comment (qdzlug) [reply docs/getting_started.md:66]: I like this idea and think we need to move towards this as a general direction.

File: extras/jenkins/Minikube/Jenkinsfile (hunk 3 above)
Comment (qdzlug) [reply extras/jenkins/Minikube/Jenkinsfile:183]: That was a bit annoying, and oddly hard to find. It was also weird that the Jenkinsfile linter did not seem to pick it up.

File: pulumi/python/kubernetes/nginx/ingress-controller-repo-only/__main__.py (hunk 4 above)
Comment (qdzlug) [reply pulumi/python/kubernetes/nginx/ingress-controller-repo-only/__main__.py:34]: Thanks for opening the issue; I think there may be 1-2 tangentially related issues that I can go and link to this one later today.

File: config/pulumi/Pulumi.stackname.yaml.example [hunk 6]
```diff
@@ -174,10 +174,10 @@ config:
...
   #
   # Github URL with a tag specified:
-  # https://github.com/nginxinc/kubernetes-ingress.git#v2.1.0
-  # git@github.com:nginxinc/kubernetes-ingress.git#v2.1.0
-  # ssh://git@github.com:nginxinc/kubernetes-ingress.git#v2.1.0
-  kic:src_url: https://github.com/nginxinc/kubernetes-ingress.git#v2.1.0
+  # https://github.com/nginxinc/kubernetes-ingress.git#v2.2.0
+  # git@github.com:nginxinc/kubernetes-ingress.git#v2.2.0
+  # ssh://git@github.com:nginxinc/kubernetes-ingress.git#v2.2.0
+  kic:src_url: https://github.com/nginxinc/kubernetes-ingress.git#v2.2.0
```
[the remark this answers is not in the document]
Comment (qdzlug) [reply config/pulumi/Pulumi.stackname.yaml.example:180]: Feature request looks good; I so want to get this all cleaned up.

File: bin/setup_venv.sh [hunk 7]
```diff
@@ -235,16 +235,34 @@ else
...
 
-# Add local kubectl to the virtual environment
+#
+# This section originally pulled the most recent version of Kubectl down; however it turned out that
+# was causing isues with our AWS deploy (see the issues in the repo). Addtionally, this was only
+# downloading the kubectl if it did not exist; this could result in versions not being updated if the
+# MARA project was run in the same environment w/o a refresh.
+#
+# The two fixes here are to hardcode (For now) to a known good version (1.23.6) and force the script to
+# always download this version.
```
[the remark this answers is not in the document]
Comment (qdzlug) [reply bin/setup_venv.sh:245]: Anytime that we are hardcoding a version into a non-standard place I want to make sure that we explain why. My thought is that anyone who starts digging into the setup_venv code will understand this.

Ideally, we will set this value at the same place as everything else; I tried to put it into requirements.txt and that failed with errors (pip tries to install it, which is weird because it doesn't try and install other things we download like pulumi).

I'm going to open up an issue to make sure contributors see this.
